# Current Aggressive Strategy Configuration  
# Exact replica of your current aggressive config for comparison

strategy_name: "current_aggressive"
description: "Your current single-wallet aggressive strategy (bleeding at 30% win rate)"

# Entry conditions - Ultra aggressive, single wallet trigger
entry:
  trigger_type: "single_wallet"  
  min_alpha_wallets: 1  # Single wallet can trigger
  max_entry_delay_seconds: 15  # Must enter within 15s
  
  # No confirmation required
  confirmation_wallets: 1
  confirmation_timeout_seconds: 0
  independence_check: false  # Disabled for speed
  
  # Position sizing
  base_position_size_pct: 0.03  # 3% of capital  
  max_concurrent_positions: 10   # High frequency

# Execution settings - Low slippage, prone to failures
execution:
  # Fixed low slippage
  slippage_ladder:
    "0-5": 0.03    # 3% across all timeframes
    "5-10": 0.03
    "10-20": 0.03
  
  # No leader price delta guard - buy at any price
  leader_price_delta_max_pct: 999.0  # Effectively disabled
  
  # Transaction settings  
  max_retries: 2
  priority_fee_range: [0.002, 0.002]  # Fixed priority fee
  use_jito_bundles: false

# Exit conditions - Current multi-tier with wide stops
exits:
  # Wide stop loss with 60s buffer
  stop_loss:
    enabled: true
    percentage: -35.0  # -35% stop loss (very wide)
    buffer_seconds: 60  # 60 second no-stop buffer
    atr_multiplier: 4.0  # Very wide ATR stops
  
  # Multi-tier take profit system
  take_profit:
    enabled: true
    
    # TP1 at +20%
    tp1_percentage: 20.0   # +20% gain
    tp1_sell_amount: 0.40  # Sell 40%
    tp1_then_breakeven: false  # No breakeven protection
    
    # TP2 at +45%  
    tp2_percentage: 45.0   # +45% gain
    tp2_sell_amount: 0.35  # Sell 35%
    
    # TP3 at +90%
    tp3_percentage: 90.0   # +90% gain  
    tp3_sell_amount: 0.20  # Sell 20%
    
    # Wide trailing stop on remainder (5% left)
    trailing_stop_enabled: true
    trailing_stop_percentage: 30.0  # 30% drawdown allowed
  
  # Remaining position management
  remaining_position:
    enabled: true
    profit_protection_level: 15.0  # Exit if drops below +15%
    trailing_stop_percentage: 20.0  # 20% trailing 
    max_remaining_hold_seconds: 10800  # 3 hours
  
  # Time-based exits - Force profits at arbitrary times
  time_based:
    max_hold_seconds: 1800  # 30 minutes max
    time_based_profits:
      - time_minutes: 15
        min_profit_pct: 15.0
      - time_minutes: 20  
        min_profit_pct: 10.0

# Safety settings - Mostly disabled for "speed"
safety:
  # Sellability checks DISABLED
  require_sellability: false
  hold_through_check: false  # Don't check if leader dumps
  
  # Low liquidity requirements
  min_liquidity_usd: 5000   # Very low threshold
  liquidity_quality_score: false
  
  # Price extension guard DISABLED
  price_extension_guard: 
    enabled: false  # Can buy at peaks
  
  # S-tier bypasses ALL safety (dangerous)
  s_tier_bypass_safety: true
  ultra_confidence_bypass: true  # 80%+ confidence bypasses everything

# Risk management - DISABLED
risk_management:
  enabled: false  # No circuit breakers
  daily_loss_circuit_breaker: 
    max_loss_usd: 999999  # Effectively disabled
    max_consecutive_losses: 999

# Simulation-specific settings
simulation:
  # Aggressive execution parameters
  execution_delay_seconds: 3.0  # Time from signal to execution
  
  # Fee structure
  entry_priority_fee_usd: 1.0   # High fixed priority fees
  exit_priority_fee_usd: 1.0
  transaction_fee_usd: 0.05
  
  # Low slippage tolerance = higher failure rates
  entry_slippage_base_pct: 2.0  # Low slippage
  exit_slippage_pct: 2.0
  panic_exit_slippage_pct: 3.0  # Panic selling
  
  # High failure rates due to low slippage tolerance
  buy_failure_rate: 0.15  # 15% of buys fail (miss winners)
  sell_failure_rate: 0.10  # 10% of sells fail
  
  # Network delays
  reconciliation_delay_seconds: 2.0
  indexing_delay_seconds: 10.0

# Why this strategy is bleeding at 30% win rate:
# 1. Single wallet triggers catch too much bait/early exit liquidity
# 2. Low slippage causes missed fills on winners, filled on losers  
# 3. 60s no-stop buffer lets bad positions get worse
# 4. -35% stop loss is too wide vs +20% first profit taking
# 5. S-tier safety bypasses remove honeypot/rug protection
# 6. No confirmation requirement = trading on noise