# Moon Chase Strategy - Simplified Version  
# Only using conditions that are actually implemented in the simulator

strategy_name: "moon_chase"
description: "Large positions on good setups - simplified"

# Entry conditions - ONLY using implemented features
entry:
  min_alpha_wallets: 3  # Need strong signal but achievable
  max_entry_delay_seconds: 20
  position_size_usd: 200.0  # Large position

# Exit conditions - Patient for big gains
exits:
  # Longer buffer for moon shots
  volatility_buffer:
    enabled: true
    buffer_seconds: 90  # 90 second buffer
    allow_take_profits_during_buffer: true
  
  # Wider stop for larger positions
  stop_loss:
    enabled: true
    percentage: -12.0  # -12% stop (room for volatility)
    applies_after_buffer: true
  
  # Multi-tier profit taking for moon shots
  take_profit:
    enabled: true
    multi_tier_enabled: true
    
    # TP1: Secure initial at 15%
    tp1_percentage: 15.0  # +15% first target
    tp1_sell_amount: 0.40  # Sell 40%
    
    # TP2: Take more at 30%
    tp2_percentage: 30.0  # +30% second target
    tp2_sell_amount: 0.30  # Sell 30% more
    
    # TP3: Big target at 50%
    tp3_percentage: 50.0  # +50% moon target
    tp3_sell_amount: 0.25  # Sell 25% more
    
    # Moon bag: 5% rides forever
    trailing_stop_enabled: true
    trailing_stop_percentage: 20.0  # 20% trailing from peak
  
  # Longer time horizon
  time_based:
    max_hold_seconds: 1800  # 30 minutes max
    force_exit_at_max: false

# Simulation settings - REALISTIC for $200 positions
simulation:
  # Higher fees for perfect setups (competitive)
  entry_priority_fee_usd: 2.0  # Higher priority for perfect setups
  exit_priority_fee_usd: 1.5  # Slightly higher exit priority
  transaction_fee_usd: 0.05
  
  # Slippage for large positions
  entry_slippage_pct: 3.0  # Higher slippage for $200
  exit_slippage_pct: 3.0
  panic_exit_slippage_pct: 5.0  # Much worse on panic
  
  # Failure rates (competitive environment)
  buy_failure_rate: 0.15  # 15% fail rate
  sell_failure_rate: 0.10