# Sniper Bot Configuration
# Focus: Early entry on tokens from whitelisted devs

network:
  cluster: "mainnet-beta"
  rpc_endpoints:
    - "https://api.mainnet-beta.solana.com"
    # Add more free endpoints or QuickNode URL here
  node_region: "us-east"
  retry_backoff_ms: 150

discovery:
  # WebSocket for real-time token creation events
  sources:
    pumpfun:
      enabled: true
      # No polling - uses WebSocket events
    solana_spl:
      enabled: false  # Future expansion
  
  # Dev profile enrichment (optimized for high throughput with batch API)
  enrichment:
    cache_ttl_hours: 24  # Cache profiles for 24 hours
    batch_interval_sec: 30  # Check for stale profiles every 30s
    max_batch_size: 50  # Max devs per batch API call (optimized for single batch query)
  
  # Dev quality thresholds
  min_prev_peak_mc_usd: 50000  # Dev must have launched ≥$50K MC token
  max_dev_launches_24h: 3  # Anti-spam
  lookback_days: 60
  watchlist_bootstrap: []  # Add initial dev pubkeys here
  bootstrap_only: false  # If true, only trade bootstrap devs

trade:
  enable_live: false  # Start with false for testing
  quote_ccy: "SOL"
  
  # Dynamic position sizing by score
  base_position_size_sol: 0.2  # ~$30 at $150/SOL
  size_by_score:
    - min_score: 80
      size_sol: 0.4
    - min_score: 65
      size_sol: 0.3
    - min_score: 50
      size_sol: 0.2
    - min_score: 0
      size_sol: 0.15
  
  max_risk_per_hour_sol: 1.0
  max_open_positions: 1
  max_trades_per_hour: 6
  
  # Dynamic priority fees with score tiers
  priority_fee_sol:
    base: 0.002
    max: 0.01
    by_score:
      - min_score: 80
        base: 0.004
        max: 0.012
      - min_score: 65
        base: 0.003
        max: 0.01
      - min_score: 0
        base: 0.002
        max: 0.008
  
  # Congestion multipliers
  congestion:
    p95_latency_ms_buckets: [150, 300, 600]
    multipliers: [1.0, 1.5, 2.0, 3.0]
  
  slippage_bps: 250  # 2.5%
  max_buy_impact_bps: 150  # Abort if impact > 1.5%

safety:
  # Dev requirements
  dev_min_hold_pct: 1.0  # Dev must retain ≥1%
  dev_max_hold_pct: 20.0  # Dev must hold <20%
  dev_min_liq_sol: 0.5  # Min initial LP (sniping mode - just enough for execution)
  dev_max_initial_buy_sol: 2.0  # Avoid farmy self-buys
  dev_no_rug_history_days: 90  # No rugs in 90 days
  
  # Token requirements
  max_tax_bps: 200  # 2% max combined tax
  max_tokens_launched_7d: 5  # Too many = farm
  min_unique_buyers_first_5min: 12  # Market breadth
  
  # Blacklist/allowlist
  blocklist:
    wallets: []
    tickers: []
  allowlist:
    wallets: []  # Overrides most checks

exit:
  # Dynamic exit for ~$30 positions
  loss_cap_pct: 20  # -20% = sell all
  
  # Adaptive trailing stop
  trailing_floor_pct_min: 18
  trailing_floor_pct_max: 30
  
  # Whale detection
  whale_sell_threshold_pct_supply: 1.5  # Top holder threshold
  whale_single_sale_pct: 35  # Single whale sells >35%
  whale_multi_topN: 10  # Track top N holders
  whale_multi_sale_pct: 25  # Multiple whales sell >25%
  whale_multi_window_sec: 120
  
  # Liquidity/volume cliff
  liq_cliff:
    vol_drop_pct: 70  # Volume drops 70%
    depth_drop_pct: 40  # Depth drops 40%
    spread_bps: 40  # Spread widens to 0.4%
    window_min: 10
  
  # Time decay
  time_decay_min_without_new_ath: 20
  
  # Partial profit taking
  partials:
    enabled: true
    steps:
      - trigger_mult: 3.0
        sell_pct: 30
      - trigger_mult: 6.0
        sell_pct: 20

storage:
  path: "data/sniper"  # JSON storage location
  rotate_jsonl_mb: 128  # Rotate event logs at 128MB

alerts:
  discord_webhook: "https://discord.com/api/webhooks/1414756971885891665/TlggbkVxMo2-b6GDNBk3HaULmvVvaeB6yCMFL-y1ewazreCxSNMz0q1Xcyn2p1ElWTZf"
  send_on:
    - "ENTRY_OK"
    - "ENTRY_ABORTED"
    - "EXIT_FILLED"
    - "RUG_ALERT"
    - "WHITELIST_UPDATE"
    - "BLACKLIST_UPDATE"

metrics:
  prometheus_port: 9109
  enabled: true

# Risk scoring weights
risk_scoring:
  weights:
    peak_mc: 30  # Historical peak market cap
    rug_count: 20  # Inverse of rug count
    holder_count: 15  # Median holders at 15m
    launch_freq: 15  # Launch frequency penalty
    lp_quality: 10  # LP lock/credible sources
    social: 10  # Optional social footprint
  
  min_score_to_trade: 50  # Minimum score to attempt entry
  
  # Per-dev throttling
  dev_cooldown_hours: 24  # Only 1 attempt per dev per day